/* Minimal LKL host autoconf for the macOS arm64 bring-up harness.
 * The full file is normally generated by tools/lkl/Makefile.autoconf from the
 * kernel .config; the host UAPI headers only consult these three macros.
 * arm64 macOS is 64-bit little-endian. */
#define LKL_CONFIG_64BIT 1
#define LKL_CONFIG_JSON_TOKEN_MAX 300
/* little-endian => LKL_CONFIG_CPU_BIG_ENDIAN intentionally left undefined */
